[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.commerce.discounts"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["discounts", "hubspot", "CRM", "commerce"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.discounts"

[build-options]
observabilityIncluded = true
